# Generated by Django 5.1.5 on 2025-05-11 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agencyplan",
            name="year",
        ),
        migrations.AddField(
            model_name="agencyplan",
            name="yearly_data",
            field=models.JSONField(
                default=dict,
                help_text="A mapping of year to numeric value, e.g. {'2023': 12.5, '2024': 15.0}",
            ),
        ),
    ]
