# Generated by Django 5.1.5 on 2025-05-11 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_remove_agencyplan_year_agencyplan_yearly_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="agencyplan",
            name="plan_type",
            field=models.IntegerField(
                choices=[
                    (1, "One Year"),
                    (3, "Three Year"),
                    (5, "Five Year"),
                    (10, "Ten Year"),
                ],
                default=1,
                help_text="Duration of the plan in years",
            ),
        ),
    ]
