from .authentication import CreateUserView, PasswordResetView
from .agency_plan import AgencyPlanListView, AgencyPlanDetailView
from .department import DepartmentListView, DepartmentDetailView
from .goals import GoalsListView, GoalsDetailView
from .director_plan import DirectorPlanListView, DirectorPlanDetailView
from .measurement import MeasurementListView, MeasurementDetailView
from .perspective import PerspectiveListView, PerspectiveDetailView
from .reports import MonthlyReportListView, MonthlyReportDetailView
from .reports import DailyReportListView, DailyReportDetailView
from .reports import MonthsListView, MonthsDetailView
from .strategicGoal import AStrategicGoalListView, DStrategicGoalListView
from .yearData import YearDataListView, YearDataDetailView
